# Generated by Django 5.2.5 on 2025-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwfapp', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
