# Generated by Django 5.2.5 on 2025-09-30 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwfapp', '0003_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='mwfapp.stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
