# Generated by Django 5.2.5 on 2025-10-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwfapp', '0004_remove_sale_product_sale_stock_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('TOTAL', 'Total'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
